config/routes.rb
Twilio::Application.routes.draw do
  devise_for :users
  root 'people#index'

  resources :people do
    resources :messages, only: [:create, :new]
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
	validates :name, presence: true
	validates :phone, presence: true, length: {minimum: 10, maximum: 10   }
	validates :partysize, presence: true, numericality: {only_integer:true, :greater_than => 0, :less_than_or_equal_to => 12 }
	validates :waitminutes, presence: true, numericality: {only_integer:true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 240  }

	before_save :calculate_seating_time

	def calculate_seating_time
		if self.created_at.blank?
			self.seating_time = (Time.now + self.waitminutes*60).strftime "%I:%M %P (%m/%d)"
		else
			self.seating_time = (self.created_at.localtime + self.waitminutes*60).strftime "%I:%M %P (%m/%d)"
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def create
		@person = Person.find(params[:person_id])
		@number = @person.phone

		@message = params[:body]
		 
		# Get your Account Sid and Auth Token from twilio.com/user/account
		account_sid = 'AC138577fdee094b3cb61fd08272e46b17'
		auth_token = '17ff50c7406edcc0a1d7c1d7a101dfc7'
		@client = Twilio::REST::Client.new(ENV["TW_SID"], ENV["TW_TOKEN"])
		 
		message = @client.account.messages.create(:body => "#{@message}",
		    :to => "#{@number}",
		    :from => ENV["TW_SOURCE"])
		puts message.to

		redirect_to root_path
		end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

before_action :authenticate_user!, only: [:new, :create]

	def index
		@people = Person.all
	end

	def show
		@people = Person.find params[:id]
	end

	def new
		@people = Person.new
	end

	def create
		safe_person_params = params.require(:person).permit(:name, :phone, :partysize, :waitminutes)
		@people = Person.new(safe_person_params)
		if @people.save
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
		@people = Person.find(params[:id])
	end

	def update
		safe_person_params = params.require(:person).permit(:name, :phone, :partysize, :waitminutes)
		@people = Person.find(params[:id])
		if @people.update(safe_person_params)
			redirect_to root_path
		else
			render :edit
		end
	end

	def destroy
		@people = Person.find(params[:id]).destroy
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/twils_helper.rb
module TwilsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantMsgr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body bgcolor="#FFFFFF">

<div class = "navbar navbar-default navbar-static-top" role = "navigation">

<div class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
 	<%= link_to "Sign Up", new_user_registration_path %> |
	<%= link_to "Sign In", new_user_session_path %>
<% end %>
</div >

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/people/_customerdetails.html.erb
<%= "Name: #{person.name}" %> <br>
<%= "Phone #: #{person.phone}" %> <br>
<%= "Party Size: #{person.partysize}" %> <br>
<%= "Given Wait Time: #{person.waitminutes} minutes" %> <br>

<%= "Estimated Seating Time: " + (person.seating_time.in_time_zone("Pacific Time (US & Canada)").strftime "%I:%M %P")  %> <br>
<!-- links below: -->
<%= link_to "Edit", edit_person_path(person.id) %> |
<%= link_to "Delete", person_path(person.id), :method => :delete %> 

<!-- Text message section below: -->
<%= form_tag person_messages_path(person.id), :method => :post do %>
<% tableready = (DateTime.strptime(person.seating_time, "%I:%M %P (%m/%d)").to_time - (Time.now-7*3600))/60%>
	<% if tableready > 0 %>
		<%= text_area_tag :body, "Your table will be ready in #{tableready.round} minutes.", placeholder: "Type your text here" %><br>
	<% else %>
		<%= text_area_tag :body, "Your table is now ready!", placeholder: "Type your text here" %><br>
	<% end %>
	<%= submit_tag "Send Message" %>

app/views/people/_editdelete.html.erb
<%= link_to "Edit", edit_person_path(person.id) %> |
<%= link_to "Delete", person_path(person.id), :method => :delete %> 

app/views/people/_form.html.erb
<%= form_for(@people) do |f| %>
	<fieldset>
		<legend>Person</legend>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :phone %>
		<%= f.text_field :phone %>
	</div>
	<div>
		<%= f.label "Party Size" %>
		<%= f.text_field :partysize %>
	</div>
	<div>
		<%= f.label "Wait Time (mins)" %>
		<%= f.text_field :waitminutes %>
	</div>
	</fieldset>
	<%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<% if @people.errors.any? %>
	<h2> The following errors prevented your person from saving: </h2>
<ul>
	<% @people.errors.full_messages.each do |msg| %>
		<li> <%= msg %> </li>
	<% end %>
</ul>
<% end %>

<li> <%= "Current time: #{Time.now.strftime "%I:%M %P (%m/%d)"}" %> </li>
<li> <%= "Time Arrived: " + (@people.created_at.in_time_zone("Pacific Time (US & Canada)").strftime "%I:%M %P (%m/%d)")  %> <br>
<li> <%= "Current estimated seating time: #{@people.seating_time}" %> </li>

<h1> Edit an existing customer: </h1>
<%= render partial: 'form' %>

app/views/people/index.html.erb
<h1> RestaurantMsgr </h1>

<h4> <%= "Current time: #{Time.now.strftime "%I:%M %P (%m/%d)"}" %> </h4>

<h5> <%= link_to "+ New customer", new_person_path %> </h5>

<!-- Quick list of waiting customers -->
<h3> Wait List </h3>
	<% sorted_people = @people.sort_by {|people| people[:seating_time]} %>
	<ol>
	<% sorted_people.each do |person| %>
		<li>
			<% if (DateTime.strptime(person.seating_time, "%I:%M %P (%m/%d)").to_time - (Time.now-7*3600)) < 0 %>
			<!-- if seating time is past due -->
				<b><font color = "red" > <%= "#{person.name} | Party of #{person.partysize} | Seating Time: #{person.seating_time} | SEATING OVERDUE" %> </font></b>
					<!-- links below: -->
					<%= link_to "Edit", edit_person_path(person.id) %> |
					<%= link_to "Delete", person_path(person.id), :method => :delete %> 
			<% else %>
				<%= "#{person.name} | Party of #{person.partysize} | Seating Time: #{person.seating_time}" %>
					<!-- links below: -->
					<%= link_to "Edit", edit_person_path(person.id) %> |
					<%= link_to "Delete", person_path(person.id), :method => :delete %>  
			<% end %>
		</li>
	<% end %>
	</ol>


<!-- Each customer's contact info, etc -->
<h3> Customer Details </h3>

<div class="row">
	<ol>
	
	<% sorted_people.each do |person| %>
		<div class = "col-md-3">
		<li>
			<% if (DateTime.strptime(person.seating_time, "%I:%M %P (%m/%d)").to_time - (Time.now-7*3600)) < 0 %>
			<!-- if seating time is past due -->
			 <font color = red > 
				<%= "Name: #{person.name}" %> <br>
				<%= "Phone #: #{person.phone}" %> <br>
				<%= "Party Size: #{person.partysize}" %> <br>
				<%= "Time Arrived: " + (person.created_at.in_time_zone("Pacific Time (US & Canada)").strftime "%I:%M %P")  %> <br>
				<%= "Given Wait Time: #{person.waitminutes} minutes" %> <br>
				<%= "Estimated Seating Time: " + (person.seating_time.in_time_zone("Pacific Time (US & Canada)").strftime "%I:%M %P")  %> <br>
				<!-- links below: -->
				<%= link_to "Edit", edit_person_path(person.id) %> |
				<%= link_to "Delete", person_path(person.id), :method => :delete %> 
			
			<!-- Text message section below: -->
			<%= form_tag person_messages_path(person.id), :method => :post do %>
				<% tableready = (DateTime.strptime(person.seating_time, "%I:%M %P (%m/%d)").to_time - (Time.now-7*3600))/60%>
					<% if tableready > 0 %>
						<%= text_area_tag :body, "Your table will be ready in #{tableready.round} minutes.", placeholder: "Type your text here" %><br>
					<% else %>
						<%= text_area_tag :body, "Your table is now ready!", placeholder: "Type your text here" %><br>
					<% end %>
					<%= submit_tag "Send Message" %>
			<% end %>
			</font>

			<% else %>
			<%= "Name: #{person.name}" %> <br>
			<%= "Phone #: #{person.phone}" %> <br>
			<%= "Party Size: #{person.partysize}" %> <br>
			<%= "Time Arrived: " + (person.created_at.in_time_zone("Pacific Time (US & Canada)").strftime "%I:%M %P")  %> <br>
			<%= "Given Wait Time: #{person.waitminutes} minutes" %> <br>
			<%= "Estimated Seating Time: " + (person.seating_time.in_time_zone("Pacific Time (US & Canada)").strftime "%I:%M %P")  %> <br>
			<!-- links below: -->
			<%= link_to "Edit", edit_person_path(person.id) %> |
			<%= link_to "Delete", person_path(person.id), :method => :delete %> 
			
			<!-- Text message section below: -->
			<%= form_tag person_messages_path(person.id), :method => :post do %>
				<% tableready = (DateTime.strptime(person.seating_time, "%I:%M %P (%m/%d)").to_time - (Time.now-7*3600))/60%>
					<% if tableready > 0 %>
						<%= text_area_tag :body, "Your table will be ready in #{tableready.round} minutes.", placeholder: "Type your text here" %><br>
					<% else %>
						<%= text_area_tag :body, "Your table is now ready!", placeholder: "Type your text here" %><br>
					<% end %>
					<%= submit_tag "Send Message" %>
			<% end %>
			<% end %>

		</li>
		</div>
	<% end %>
	
	</ol>
</div>

app/views/people/new.html.erb
<% if @people.errors.any? %>
	<h2> The following errors prevented your person from saving: </h2>
<ul>
	<% @people.errors.full_messages.each do |msg| %>
		<li> <%= msg %> </li>
	<% end %>
</ul>
<% end %>

<li> <%= "Current time: #{Time.now.strftime "%I:%M %P (%m/%d)"}" %> </li>

<h1> Add a new customer: </h1>
<%= render partial: 'form' %>